# PostgreSQL 18 - Docker Compose Service
# Uncomment in devcontainer.json: "../compose/postgres.compose.yml"

services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devdb
    
    ports:
      - "15432:5432"  # Host:Container - +10000 offset avoids conflicts
    
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  postgres-data:
