# SQL Server 2025 - Docker Compose Service
# Uncomment in devcontainer.json: "../compose/sqlserver.compose.yml"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    restart: unless-stopped
    
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"  # Free developer edition
    
    ports:
      - "11433:1433"  # Host:Container - +10000 offset avoids conflicts
    
    volumes:
      - sqlserver-data:/var/opt/mssql
    
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s

volumes:
  sqlserver-data:
